const defaults = { seats: 210, foodRate: 80, weekdayOccupancy: 35, weekendOccupancy: 45, weekdayRate: 200, weekendRate: 250, investorShare: 25, investment: 22500000 };
const ids = Object.keys(defaults);
const $ = (id) => document.getElementById(id);
const currency = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const shortCurrency = (value) => {
  const abs = Math.abs(value);
  if (abs >= 10000000) return `₹${(value / 10000000).toFixed(2)} Cr`;
  if (abs >= 100000) return `₹${(value / 100000).toFixed(2)} L`;
  return currency.format(value);
};
const number = (id) => Number($(id).value) || 0;

function model() {
  const seats = number('seats');
  const weekdayBookings = seats * 3 * 18 * number('weekdayOccupancy') / 100;
  const weekendBookings = seats * 4 * 12 * number('weekendOccupancy') / 100;
  const weekdayRevenue = weekdayBookings * number('weekdayRate');
  const weekendRevenue = weekendBookings * number('weekendRate');
  const ticketIncome = weekdayRevenue + weekendRevenue;
  const gstTicket = ticketIncome * 18 / 118;
  const showTax = (30 * 4) * 25;
  const foodIncome = (weekdayBookings + weekendBookings) * number('foodRate');
  const foodTax = foodIncome * 5 / 105;
  const totalIncome = ticketIncome + foodIncome;
  const taxes = gstTicket + showTax + foodTax;
  const available = totalIncome - taxes;
  const monthlyShare = available * number('investorShare') / 100;
  const annualShare = monthlyShare * 12;
  const investment = number('investment');
  const depreciation = [investment * .1, investment * .09, investment * .081];
  const yearlyShare = [annualShare, annualShare * 1.08, annualShare * 1.08 * 1.08];
  const cumulative = [];
  yearlyShare.reduce((sum, amount, i) => { const total = sum + amount + depreciation[i]; cumulative.push(total); return total; }, 0);
  return { seats, weekdayBookings, weekendBookings, weekdayRevenue, weekendRevenue, ticketIncome, foodIncome, taxes, totalIncome, available, monthlyShare, annualShare, investment, yearlyShare, cumulative };
}
function update() {
  const d = model();
  $('weekdayOccupancyValue').value = `${number('weekdayOccupancy')}%`;
  $('weekendOccupancyValue').value = `${number('weekendOccupancy')}%`;
  $('investorShareValue').value = `${number('investorShare')}%`;
  $('investmentHero').textContent = shortCurrency(d.investment);
  $('monthlyShare').textContent = shortCurrency(d.monthlyShare);
  $('annualShareNote').textContent = `${shortCurrency(d.annualShare)} annually`;
  $('totalIncome').textContent = shortCurrency(d.totalIncome);
  $('yearOneYield').textContent = d.investment ? `${(d.annualShare / d.investment * 100).toFixed(1)}%` : '—';
  $('yearOneValue').textContent = `${shortCurrency(d.annualShare)} before depreciation`;
  $('threeYearReturn').textContent = shortCurrency(d.cumulative[2]);
  $('threeYearPercent').textContent = d.investment ? `${(d.cumulative[2] / d.investment * 100).toFixed(1)}% of initial investment` : '—';
  $('grossRevenue').textContent = shortCurrency(d.available);
  $('ticketRevenue').textContent = shortCurrency(d.ticketIncome);
  $('foodRevenue').textContent = shortCurrency(d.foodIncome);
  $('taxRevenue').textContent = shortCurrency(d.taxes);
  $('availableForSharing').textContent = shortCurrency(d.available);
  const totalForDonut = d.totalIncome || 1;
  const ticketEnd = d.ticketIncome / totalForDonut * 100;
  const foodEnd = ticketEnd + d.foodIncome / totalForDonut * 100;
  $('revenueDonut').style.background = `conic-gradient(var(--purple) 0 ${ticketEnd}%, var(--teal) ${ticketEnd}% ${foodEnd}%, #e9eaf0 ${foodEnd}% 100%)`;
  $('weekdayShows').textContent = '54'; $('weekendShows').textContent = '48';
  $('weekdayBookings').textContent = Math.round(d.weekdayBookings).toLocaleString('en-IN');
  $('weekendBookings').textContent = Math.round(d.weekendBookings).toLocaleString('en-IN');
  $('weekdayRevenue').textContent = shortCurrency(d.weekdayRevenue);
  $('weekendRevenue').textContent = shortCurrency(d.weekendRevenue);
  const max = Math.max(...d.cumulative, 1);
  [['barOne', 'barOneValue', 0], ['barTwo', 'barTwoValue', 1], ['barThree', 'barThreeValue', 2]].forEach(([bar, value, i]) => { $(bar).style.height = `${Math.max(8, d.cumulative[i] / max * 142)}px`; $(value).textContent = shortCurrency(d.cumulative[i]); });
  const payback = d.annualShare ? d.investment / d.annualShare : 0;
  $('payback').textContent = payback ? `Payback in ${payback.toFixed(1)} years` : 'Payback unavailable';
}
ids.forEach((id) => $(id).addEventListener('input', update));
$('resetButton').addEventListener('click', () => { ids.forEach((id) => { $(id).value = defaults[id]; }); update(); });
$('exportButton').addEventListener('click', () => { const d = model(); const text = `FRAMEHOUSE ROI SUMMARY\n\nInitial investment: ${currency.format(d.investment)}\nMonthly total income: ${currency.format(d.totalIncome)}\nMonthly investor share: ${currency.format(d.monthlyShare)}\nAnnual investor share: ${currency.format(d.annualShare)}\nThree-year cumulative return: ${currency.format(d.cumulative[2])}`; const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(new Blob([text], { type: 'text/plain' })), download: 'framehouse-roi-summary.txt' }); link.click(); URL.revokeObjectURL(link.href); $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2400); });
update();
